### ISSUE TITLE
[Feature Idea] Permanent Triple Green Shell on Seeker to expand hitbox

### ISSUE THREAD

**Issue by TheWitheredStriker** [CLF78/HideNSeek#5]
Hi there!

While watching videos of the Hide and Seek gamemode on YouTube, I noticed a recurring issue where the lag often causes it not to register when the Seeker successfully strikes a Hider. In the comment section of [one such video](https://www.youtube.com/watch?v=YPrg29DZQeA), YouTube user [Playingwithmahwii](https://www.youtube.com/channel/UCJgCjXvH92cDVNF4CYB1vQA) suggested an interesting solution to this problem:

![image](https://user-images.githubusercontent.com/38614982/147840665-3b68162c-49da-4833-811d-f7c4927a897b.png)

This idea received support from fellow YouTube user [Formy](https://www.youtube.com/channel/UCpFVa9NiiGuVzdjj3QGCT2Q), who pointed out that this would make the act of juking seekers much riskier. I agree that it sounds like an interesting solution.

Would it be feasible or practical to implement something like this?

**Comment by CLF78** [comment]
The physical hitbox (which you cannot see) is already 1.25x larger than the original game's, and due to it being a sphere it cannot be enlarged further as it will count non-existing collisions on top/bottom. What can (and will be) done instead is remove the rest of the game's fluid movement code so that the position on everyone's screen is slightly more accurate than it is now. Anything else is pretty much a gimmick and does not contribute to fixing the problem, so no thanks.

**Comment by TheWitheredStriker** [comment]
Aha, gotcha. Thanks for getting back to me. Looking forward to seeing the better solution be implemented!
